#!/bin/sh

unset VERSIONTOOL_BUMP_RELEASE

../../bin/sml \$smlnj/compiler/all.cm <<stop
(*
Alpha32UnixCMB.make () before Alpha32UnixCMB.reset () andalso
HppaUnixCMB.make () before HppaUnixCMB.reset () andalso
*)
PPCUnixCMB.make () before PPCUnixCMB.reset () andalso
SparcUnixCMB.make () before SparcUnixCMB.reset () andalso
X86UnixCMB.make () before X86UnixCMB.reset () andalso
X86Win32CMB.make () before X86Win32CMB.reset ();
stop

#TARGETS="alpha32-unix hppa-unix ppc-unix sparc-unix x86-unix x86-win32"
TARGETS="ppc-unix sparc-unix x86-unix x86-win32"

for target in $TARGETS ; do
  dir=sml.boot.$target
  if test -d $dir ; then
    tar -cf - $dir | gzip > boot.$target.tgz
  fi
done

