#!/bin/sh
#
# Wrapper for ml-flex heap image
#

case `uname -s` in
  Darwin) heap=ml-flex.ppc-darwin ;;
  *) heap=ml-flex.x86-linux ;;
esac

if test ! -r $heap ; then
  echo "ml-flex: no heap image!"
  exit 1
fi

exec sml @SMLload=$heap $@

