(*
 * This file was automatically generated by MDGen
 * from the machine description file "x86/x86.md".
 *)


signature X86CELLS =
sig
   datatype mycellkind =
     UNKNOWN
   | MEM
   | CTRL
   | CC
   | FP
   | GP
   withtype cellset = (int list * int list * int list)
   include CELLS_BASIS where type cellkind = mycellkind
   val showCC : cell -> string
   val showFP : cell -> string
   val showGP : cell -> string
   val addGP : (cell * cellset) -> cellset
   val addFP : (cell * cellset) -> cellset
   val addCC : (cell * cellset) -> cellset
   val edi : cell
   val ebp : cell
   val fasmTmp : cell
   val stackptrR : cell
   val eax : cell
   val ebx : cell
   val ecx : cell
   val esi : cell
   val edx : cell
   val asmTmpR : cell
   val esp : cell
   val zeroReg : cellkind -> cell option
   val toString : cellkind -> cell -> string
   val addCell : cellkind -> cell * cellset -> cellset
   val rmvCell : cellkind -> cell * cellset -> cellset
   val addReg : cell * cellset -> cellset
   val rmvReg : cell * cellset -> cellset
   val addFreg : cell * cellset -> cellset
   val rmvFreg : cell * cellset -> cellset
   val getCell : cellkind -> cellset -> cell list
   val updateCell : cellkind -> cellset * cell list -> cellset
   val empty : cellset
   val cellsetToString : cellset -> string
   val cellsetToString' : (cell -> cell) -> cellset -> string
   val cellsetToCells : cellset -> cell list
end

structure X86Cells : X86CELLS =
struct
   datatype mycellkind =
     UNKNOWN
   | MEM
   | CTRL
   | CC
   | FP
   | GP
   withtype cellset = (int list * int list * int list)
   exception X86Cells
   structure SL = SortedList
   fun error msg = MLRiscErrorMsg.error("X86Cells",msg)
   val cellkindToString = (fn CC => "CC"
                            | FP => "FP"
                            | GP => "GP"
                            | MEM => "MEM"
                            | CTRL => "CTRL"
                            | UNKNOWN => "UNKNOWN"
                          )
   structure MyCellsBasis = CellsBasisFn
      (type cellkind = mycellkind
       exception Cells = X86Cells
       val unknown = UNKNOWN
       val cellkindToString = cellkindToString
       val INT = GP
       val FLOAT = FP
       val firstPseudo = 256
       val kinds = [CC, FP, GP, MEM, CTRL]
       val physical = [{from=64, to=0, kind=CC}, {from=32, to=63, kind=FP}, {from=0, to=31, kind=GP}]
      )

   open MyCellsBasis
   val offsetCC = 64
  and offsetFP = 32
  and offsetGP = 0
  and cellnames = ["CC", "FP", "GP"]
  and cellsetnames = ["GP", "FP", "CC"]
   val edi = (7 + offsetGP)
   val ebp = (5 + offsetGP)
   val fasmTmp = (~ 1)
   val stackptrR = (4 + offsetGP)
   val eax = (0 + offsetGP)
   val ebx = (3 + offsetGP)
   val ecx = (1 + offsetGP)
   val esi = (6 + offsetGP)
   val edx = (2 + offsetGP)
   val asmTmpR = (~ 1)
   val esp = (4 + offsetGP)

   fun showCC r = let
          val r = (if (r <= 0)
                then (r - 64)
                else r)
       in ((fn _ => "cc"
           ) r)
       end

   and showFP r = let
          val r = (if (r <= 63)
                then (r - 32)
                else r)
       in ((fn f => (if (f >= 0)andalso (f < 8)
                  then (("%st(" ^ (Int.toString f)) ^ ")")
                  else ("%f" ^ (Int.toString f)))
           ) r)
       end

   and showGP r = ((fn 0 => "%eax"
                     | 1 => "%ecx"
                     | 2 => "%edx"
                     | 3 => "%ebx"
                     | 4 => "%esp"
                     | 5 => "%ebp"
                     | 6 => "%esi"
                     | 7 => "%edi"
                     | r => ("%" ^ (Int.toString r))
                   ) r)
   and toString CC = showCC
     | toString FP = showFP
     | toString GP = showGP
     | toString MEM = (fn r => ("m" ^ (Int.toString r))
                      )
     | toString CTRL = (fn r => ("ctrl" ^ (Int.toString r))
                       )
     | toString UNKNOWN = (fn r => ("unknown" ^ (Int.toString r))
                          )
   val empty = ([], [], [])

   fun addCell GP = addGP
     | addCell FP = addFP
     | addCell CC = addCC
     | addCell _ = (error "addCell")
   and rmvCell GP = rmvGP
     | rmvCell FP = rmvFP
     | rmvCell CC = rmvCC
     | rmvCell _ = (error "rmvCell")
   and getCell GP = getCellGP
     | getCell FP = getCellFP
     | getCell CC = getCellCC
     | getCell _ = (error "getCell")
   and updateCell GP = updateCellGP
     | updateCell FP = updateCellFP
     | updateCell CC = updateCellCC
     | updateCell _ = (error "updateCell")
   and addGP (r, (setGP, setFP, setCC)) = ((SL.enter (r, setGP)), setFP, setCC)
   and addFP (r, (setGP, setFP, setCC)) = (setGP, (SL.enter (r, setFP)), setCC)
   and addCC (r, (setGP, setFP, setCC)) = (setGP, setFP, (SL.enter (r, setCC)))
   and rmvGP (r, (setGP, setFP, setCC)) = ((SL.rmv (r, setGP)), setFP, setCC)
   and rmvFP (r, (setGP, setFP, setCC)) = (setGP, (SL.rmv (r, setFP)), setCC)
   and rmvCC (r, (setGP, setFP, setCC)) = (setGP, setFP, (SL.rmv (r, setCC)))
   and getCellGP (setGP, setFP, setCC) = setGP
   and getCellFP (setGP, setFP, setCC) = setFP
   and getCellCC (setGP, setFP, setCC) = setCC
   and updateCellGP ((setGP, setFP, setCC), r) = (r, setFP, setCC)
   and updateCellFP ((setGP, setFP, setCC), r) = (setGP, r, setCC)
   and updateCellCC ((setGP, setFP, setCC), r) = (setGP, setFP, r)
   and cellsetToString (setGP, setFP, setCC) = (printTuple (cellsetnames, [((printSet showGP) setGP), ((printSet showFP) setFP), ((printSet showCC) setCC)]))
   and cellsetToString' regmap = (fn (setGP, setFP, setCC) => (printTuple (cellsetnames, [((printSet showGP) ((map regmap) setGP)), ((printSet showFP) ((map regmap) setFP)), ((printSet showCC) ((map regmap) setCC))]))
                                 )
   and cellsetToCells (setGP, setFP, setCC) = (setGP @ (setFP @ setCC))
   val addReg = addGP
   val addFreg = addFP
   val rmvReg = rmvFP
   val rmvFreg = rmvFP

   fun zeroReg _ = NONE
end

