# Generated makefile
#

MLDOC_BIN = /Users/jhr/bin

EXTRACT_INFO = $(MLDOC_BIN)/extract-info
HTML_GEN = $(MLDOC_BIN)/html-gen
HTML_INDEX = $(MLDOC_BIN)/html-index
HTML_TOC = $(MLDOC_BIN)/html-toc
LATEX_GEN = $(MLDOC_BIN)/latex-gen
MERGE_INFO = $(MLDOC_BIN)/merge-info
PROOF_LATEX = $(MLDOC_BIN)/proof-latex
RUN_LATEX = $(MLDOC_BIN)/run-latex
DVIPS = dvips

SRC_DIR = ML-Doc
INFO_DIR = INDEX
HTML_DIR = HTML
LATEX_DIR = Hardcopy
PROOF_DIR = Proof

CONFIG = Config.cfg CATALOG
HTML_INFO = $(CONFIG) $(INFO_DIR)/HTML.info
LATEX_INFO = $(CONFIG) $(INFO_DIR)/LaTeX.info

HTML_INFO_FILES =	$(INFO_DIR)/HashCons/hash-cons.info \
	$(INFO_DIR)/intro-part.info \
	$(INFO_DIR)/RegExp/engine-sig.info \
	$(INFO_DIR)/RegExp/match-tree.info \
	$(INFO_DIR)/RegExp/parser-sig.info \
	$(INFO_DIR)/RegExp/regexp-fn.info \
	$(INFO_DIR)/RegExp/regexp-intro.info \
	$(INFO_DIR)/RegExp/regexp-lib-part.info \
	$(INFO_DIR)/RegExp/regexp-sig.info \
	$(INFO_DIR)/RegExp/syntax.info \
	$(INFO_DIR)/smlnj-lib.info \
	$(INFO_DIR)/Util/array-qsort-fn.info \
	$(INFO_DIR)/Util/array-qsort.info \
	$(INFO_DIR)/Util/array-sort.info \
	$(INFO_DIR)/Util/atom.info \
	$(INFO_DIR)/Util/binary-map-fn.info \
	$(INFO_DIR)/Util/binary-set-fn.info \
	$(INFO_DIR)/Util/bit-array.info \
	$(INFO_DIR)/Util/bit-vector.info \
	$(INFO_DIR)/Util/bsearch.info \
	$(INFO_DIR)/Util/char-map.info \
	$(INFO_DIR)/Util/dynamic-array.info \
	$(INFO_DIR)/Util/fifo.info \
	$(INFO_DIR)/Util/iterate.info \
	$(INFO_DIR)/Util/lib-base.info \
	$(INFO_DIR)/Util/list-format.info \
	$(INFO_DIR)/Util/list-map-fn.info \
	$(INFO_DIR)/Util/list-set-fn.info \
	$(INFO_DIR)/Util/list-xprod.info \
	$(INFO_DIR)/Util/listsort.info \
	$(INFO_DIR)/Util/mono-array-sort.info \
	$(INFO_DIR)/Util/mono-dynamic-array.info \
	$(INFO_DIR)/Util/ord-key.info \
	$(INFO_DIR)/Util/ord-map.info \
	$(INFO_DIR)/Util/ord-set.info \
	$(INFO_DIR)/Util/queue.info \
	$(INFO_DIR)/Util/rand.info \
	$(INFO_DIR)/Util/random.info \
	$(INFO_DIR)/Util/splay-map-fn.info \
	$(INFO_DIR)/Util/splay-set-fn.info \
	$(INFO_DIR)/Util/splaytree.info \
	$(INFO_DIR)/Util/uref.info \
	$(INFO_DIR)/Util/util-lib-part.info

LATEX_INFO_FILES =	$(INFO_DIR)/HashCons/hash-cons.info \
	$(INFO_DIR)/intro-part.info \
	$(INFO_DIR)/RegExp/engine-sig.info \
	$(INFO_DIR)/RegExp/match-tree.info \
	$(INFO_DIR)/RegExp/parser-sig.info \
	$(INFO_DIR)/RegExp/regexp-fn.info \
	$(INFO_DIR)/RegExp/regexp-intro.info \
	$(INFO_DIR)/RegExp/regexp-lib-part.info \
	$(INFO_DIR)/RegExp/regexp-sig.info \
	$(INFO_DIR)/RegExp/syntax.info \
	$(INFO_DIR)/smlnj-lib.info \
	$(INFO_DIR)/Util/array-qsort-fn.info \
	$(INFO_DIR)/Util/array-qsort.info \
	$(INFO_DIR)/Util/array-sort.info \
	$(INFO_DIR)/Util/atom.info \
	$(INFO_DIR)/Util/binary-map-fn.info \
	$(INFO_DIR)/Util/binary-set-fn.info \
	$(INFO_DIR)/Util/bit-array.info \
	$(INFO_DIR)/Util/bit-vector.info \
	$(INFO_DIR)/Util/bsearch.info \
	$(INFO_DIR)/Util/char-map.info \
	$(INFO_DIR)/Util/dynamic-array.info \
	$(INFO_DIR)/Util/fifo.info \
	$(INFO_DIR)/Util/iterate.info \
	$(INFO_DIR)/Util/lib-base.info \
	$(INFO_DIR)/Util/list-format.info \
	$(INFO_DIR)/Util/list-map-fn.info \
	$(INFO_DIR)/Util/list-set-fn.info \
	$(INFO_DIR)/Util/list-xprod.info \
	$(INFO_DIR)/Util/listsort.info \
	$(INFO_DIR)/Util/mono-array-sort.info \
	$(INFO_DIR)/Util/mono-dynamic-array.info \
	$(INFO_DIR)/Util/ord-key.info \
	$(INFO_DIR)/Util/ord-map.info \
	$(INFO_DIR)/Util/ord-set.info \
	$(INFO_DIR)/Util/queue.info \
	$(INFO_DIR)/Util/rand.info \
	$(INFO_DIR)/Util/random.info \
	$(INFO_DIR)/Util/splay-map-fn.info \
	$(INFO_DIR)/Util/splay-set-fn.info \
	$(INFO_DIR)/Util/splaytree.info \
	$(INFO_DIR)/Util/uref.info \
	$(INFO_DIR)/Util/util-lib-part.info

HTML_FILES =	$(HTML_DIR)/index-all.html \
	$(HTML_DIR)/toc.html \
	$(HTML_DIR)/HashCons/hash-cons.html \
	$(HTML_DIR)/intro-part.html \
	$(HTML_DIR)/RegExp/engine-sig.html \
	$(HTML_DIR)/RegExp/match-tree.html \
	$(HTML_DIR)/RegExp/parser-sig.html \
	$(HTML_DIR)/RegExp/regexp-fn.html \
	$(HTML_DIR)/RegExp/regexp-intro.html \
	$(HTML_DIR)/RegExp/regexp-lib-part.html \
	$(HTML_DIR)/RegExp/regexp-sig.html \
	$(HTML_DIR)/RegExp/syntax.html \
	$(HTML_DIR)/smlnj-lib.html \
	$(HTML_DIR)/Util/array-qsort-fn.html \
	$(HTML_DIR)/Util/array-qsort.html \
	$(HTML_DIR)/Util/array-sort.html \
	$(HTML_DIR)/Util/atom.html \
	$(HTML_DIR)/Util/binary-map-fn.html \
	$(HTML_DIR)/Util/binary-set-fn.html \
	$(HTML_DIR)/Util/bit-array.html \
	$(HTML_DIR)/Util/bit-vector.html \
	$(HTML_DIR)/Util/bsearch.html \
	$(HTML_DIR)/Util/char-map.html \
	$(HTML_DIR)/Util/dynamic-array.html \
	$(HTML_DIR)/Util/fifo.html \
	$(HTML_DIR)/Util/iterate.html \
	$(HTML_DIR)/Util/lib-base.html \
	$(HTML_DIR)/Util/list-format.html \
	$(HTML_DIR)/Util/list-map-fn.html \
	$(HTML_DIR)/Util/list-set-fn.html \
	$(HTML_DIR)/Util/list-xprod.html \
	$(HTML_DIR)/Util/listsort.html \
	$(HTML_DIR)/Util/mono-array-sort.html \
	$(HTML_DIR)/Util/mono-dynamic-array.html \
	$(HTML_DIR)/Util/ord-key.html \
	$(HTML_DIR)/Util/ord-map.html \
	$(HTML_DIR)/Util/ord-set.html \
	$(HTML_DIR)/Util/queue.html \
	$(HTML_DIR)/Util/rand.html \
	$(HTML_DIR)/Util/random.html \
	$(HTML_DIR)/Util/splay-map-fn.html \
	$(HTML_DIR)/Util/splay-set-fn.html \
	$(HTML_DIR)/Util/splaytree.html \
	$(HTML_DIR)/Util/uref.html \
	$(HTML_DIR)/Util/util-lib-part.html

LATEX_FILES =	$(LATEX_DIR)/HashCons/hash-cons.tex \
	$(LATEX_DIR)/intro-part.tex \
	$(LATEX_DIR)/RegExp/engine-sig.tex \
	$(LATEX_DIR)/RegExp/match-tree.tex \
	$(LATEX_DIR)/RegExp/parser-sig.tex \
	$(LATEX_DIR)/RegExp/regexp-fn.tex \
	$(LATEX_DIR)/RegExp/regexp-intro.tex \
	$(LATEX_DIR)/RegExp/regexp-lib-part.tex \
	$(LATEX_DIR)/RegExp/regexp-sig.tex \
	$(LATEX_DIR)/RegExp/syntax.tex \
	$(LATEX_DIR)/smlnj-lib.tex \
	$(LATEX_DIR)/Util/array-qsort-fn.tex \
	$(LATEX_DIR)/Util/array-qsort.tex \
	$(LATEX_DIR)/Util/array-sort.tex \
	$(LATEX_DIR)/Util/atom.tex \
	$(LATEX_DIR)/Util/binary-map-fn.tex \
	$(LATEX_DIR)/Util/binary-set-fn.tex \
	$(LATEX_DIR)/Util/bit-array.tex \
	$(LATEX_DIR)/Util/bit-vector.tex \
	$(LATEX_DIR)/Util/bsearch.tex \
	$(LATEX_DIR)/Util/char-map.tex \
	$(LATEX_DIR)/Util/dynamic-array.tex \
	$(LATEX_DIR)/Util/fifo.tex \
	$(LATEX_DIR)/Util/iterate.tex \
	$(LATEX_DIR)/Util/lib-base.tex \
	$(LATEX_DIR)/Util/list-format.tex \
	$(LATEX_DIR)/Util/list-map-fn.tex \
	$(LATEX_DIR)/Util/list-set-fn.tex \
	$(LATEX_DIR)/Util/list-xprod.tex \
	$(LATEX_DIR)/Util/listsort.tex \
	$(LATEX_DIR)/Util/mono-array-sort.tex \
	$(LATEX_DIR)/Util/mono-dynamic-array.tex \
	$(LATEX_DIR)/Util/ord-key.tex \
	$(LATEX_DIR)/Util/ord-map.tex \
	$(LATEX_DIR)/Util/ord-set.tex \
	$(LATEX_DIR)/Util/queue.tex \
	$(LATEX_DIR)/Util/rand.tex \
	$(LATEX_DIR)/Util/random.tex \
	$(LATEX_DIR)/Util/splay-map-fn.tex \
	$(LATEX_DIR)/Util/splay-set-fn.tex \
	$(LATEX_DIR)/Util/splaytree.tex \
	$(LATEX_DIR)/Util/uref.tex \
	$(LATEX_DIR)/Util/util-lib-part.tex

PROOF_FILES =	$(PROOF_DIR)/HashCons/hash-cons.tex \
	$(PROOF_DIR)/intro-part.tex \
	$(PROOF_DIR)/RegExp/engine-sig.tex \
	$(PROOF_DIR)/RegExp/match-tree.tex \
	$(PROOF_DIR)/RegExp/parser-sig.tex \
	$(PROOF_DIR)/RegExp/regexp-fn.tex \
	$(PROOF_DIR)/RegExp/regexp-intro.tex \
	$(PROOF_DIR)/RegExp/regexp-lib-part.tex \
	$(PROOF_DIR)/RegExp/regexp-sig.tex \
	$(PROOF_DIR)/RegExp/syntax.tex \
	$(PROOF_DIR)/smlnj-lib.tex \
	$(PROOF_DIR)/Util/array-qsort-fn.tex \
	$(PROOF_DIR)/Util/array-qsort.tex \
	$(PROOF_DIR)/Util/array-sort.tex \
	$(PROOF_DIR)/Util/atom.tex \
	$(PROOF_DIR)/Util/binary-map-fn.tex \
	$(PROOF_DIR)/Util/binary-set-fn.tex \
	$(PROOF_DIR)/Util/bit-array.tex \
	$(PROOF_DIR)/Util/bit-vector.tex \
	$(PROOF_DIR)/Util/bsearch.tex \
	$(PROOF_DIR)/Util/char-map.tex \
	$(PROOF_DIR)/Util/dynamic-array.tex \
	$(PROOF_DIR)/Util/fifo.tex \
	$(PROOF_DIR)/Util/iterate.tex \
	$(PROOF_DIR)/Util/lib-base.tex \
	$(PROOF_DIR)/Util/list-format.tex \
	$(PROOF_DIR)/Util/list-map-fn.tex \
	$(PROOF_DIR)/Util/list-set-fn.tex \
	$(PROOF_DIR)/Util/list-xprod.tex \
	$(PROOF_DIR)/Util/listsort.tex \
	$(PROOF_DIR)/Util/mono-array-sort.tex \
	$(PROOF_DIR)/Util/mono-dynamic-array.tex \
	$(PROOF_DIR)/Util/ord-key.tex \
	$(PROOF_DIR)/Util/ord-map.tex \
	$(PROOF_DIR)/Util/ord-set.tex \
	$(PROOF_DIR)/Util/queue.tex \
	$(PROOF_DIR)/Util/rand.tex \
	$(PROOF_DIR)/Util/random.tex \
	$(PROOF_DIR)/Util/splay-map-fn.tex \
	$(PROOF_DIR)/Util/splay-set-fn.tex \
	$(PROOF_DIR)/Util/splaytree.tex \
	$(PROOF_DIR)/Util/uref.tex \
	$(PROOF_DIR)/Util/util-lib-part.tex

HTML:	$(HTML_FILES)

$(HTML_DIR)/toc.html:	$(HTML_INFO) toc.template
	$(HTML_TOC)

$(HTML_DIR)/index-all.html:	$(HTML_INFO) index.template
	$(HTML_INDEX) -all

$(HTML_DIR)/HashCons/hash-cons.html:	$(SRC_DIR)/HashCons/hash-cons.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/HashCons/hash-cons.mldoc

$(HTML_DIR)/intro-part.html:	$(SRC_DIR)/intro-part.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/intro-part.mldoc

$(HTML_DIR)/RegExp/engine-sig.html:	$(SRC_DIR)/RegExp/engine-sig.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/engine-sig.mldoc

$(HTML_DIR)/RegExp/match-tree.html:	$(SRC_DIR)/RegExp/match-tree.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/match-tree.mldoc

$(HTML_DIR)/RegExp/parser-sig.html:	$(SRC_DIR)/RegExp/parser-sig.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/parser-sig.mldoc

$(HTML_DIR)/RegExp/regexp-fn.html:	$(SRC_DIR)/RegExp/regexp-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/regexp-fn.mldoc

$(HTML_DIR)/RegExp/regexp-intro.html:	$(SRC_DIR)/RegExp/regexp-intro.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/regexp-intro.mldoc

$(HTML_DIR)/RegExp/regexp-lib-part.html:	$(SRC_DIR)/RegExp/regexp-lib-part.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/regexp-lib-part.mldoc

$(HTML_DIR)/RegExp/regexp-sig.html:	$(SRC_DIR)/RegExp/regexp-sig.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/regexp-sig.mldoc

$(HTML_DIR)/RegExp/syntax.html:	$(SRC_DIR)/RegExp/syntax.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/RegExp/syntax.mldoc

$(HTML_DIR)/smlnj-lib.html:	$(SRC_DIR)/smlnj-lib.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/smlnj-lib.mldoc

$(HTML_DIR)/Util/array-qsort-fn.html:	$(SRC_DIR)/Util/array-qsort-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/array-qsort-fn.mldoc

$(HTML_DIR)/Util/array-qsort.html:	$(SRC_DIR)/Util/array-qsort.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/array-qsort.mldoc

$(HTML_DIR)/Util/array-sort.html:	$(SRC_DIR)/Util/array-sort.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/array-sort.mldoc

$(HTML_DIR)/Util/atom.html:	$(SRC_DIR)/Util/atom.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/atom.mldoc

$(HTML_DIR)/Util/binary-map-fn.html:	$(SRC_DIR)/Util/binary-map-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/binary-map-fn.mldoc

$(HTML_DIR)/Util/binary-set-fn.html:	$(SRC_DIR)/Util/binary-set-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/binary-set-fn.mldoc

$(HTML_DIR)/Util/bit-array.html:	$(SRC_DIR)/Util/bit-array.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/bit-array.mldoc

$(HTML_DIR)/Util/bit-vector.html:	$(SRC_DIR)/Util/bit-vector.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/bit-vector.mldoc

$(HTML_DIR)/Util/bsearch.html:	$(SRC_DIR)/Util/bsearch.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/bsearch.mldoc

$(HTML_DIR)/Util/char-map.html:	$(SRC_DIR)/Util/char-map.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/char-map.mldoc

$(HTML_DIR)/Util/dynamic-array.html:	$(SRC_DIR)/Util/dynamic-array.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/dynamic-array.mldoc

$(HTML_DIR)/Util/fifo.html:	$(SRC_DIR)/Util/fifo.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/fifo.mldoc

$(HTML_DIR)/Util/iterate.html:	$(SRC_DIR)/Util/iterate.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/iterate.mldoc

$(HTML_DIR)/Util/lib-base.html:	$(SRC_DIR)/Util/lib-base.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/lib-base.mldoc

$(HTML_DIR)/Util/list-format.html:	$(SRC_DIR)/Util/list-format.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/list-format.mldoc

$(HTML_DIR)/Util/list-map-fn.html:	$(SRC_DIR)/Util/list-map-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/list-map-fn.mldoc

$(HTML_DIR)/Util/list-set-fn.html:	$(SRC_DIR)/Util/list-set-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/list-set-fn.mldoc

$(HTML_DIR)/Util/list-xprod.html:	$(SRC_DIR)/Util/list-xprod.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/list-xprod.mldoc

$(HTML_DIR)/Util/listsort.html:	$(SRC_DIR)/Util/listsort.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/listsort.mldoc

$(HTML_DIR)/Util/mono-array-sort.html:	$(SRC_DIR)/Util/mono-array-sort.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/mono-array-sort.mldoc

$(HTML_DIR)/Util/mono-dynamic-array.html:	$(SRC_DIR)/Util/mono-dynamic-array.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/mono-dynamic-array.mldoc

$(HTML_DIR)/Util/ord-key.html:	$(SRC_DIR)/Util/ord-key.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/ord-key.mldoc

$(HTML_DIR)/Util/ord-map.html:	$(SRC_DIR)/Util/ord-map.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/ord-map.mldoc

$(HTML_DIR)/Util/ord-set.html:	$(SRC_DIR)/Util/ord-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/ord-set.mldoc

$(HTML_DIR)/Util/queue.html:	$(SRC_DIR)/Util/queue.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/queue.mldoc

$(HTML_DIR)/Util/rand.html:	$(SRC_DIR)/Util/rand.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/rand.mldoc

$(HTML_DIR)/Util/random.html:	$(SRC_DIR)/Util/random.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/random.mldoc

$(HTML_DIR)/Util/splay-map-fn.html:	$(SRC_DIR)/Util/splay-map-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/splay-map-fn.mldoc

$(HTML_DIR)/Util/splay-set-fn.html:	$(SRC_DIR)/Util/splay-set-fn.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/splay-set-fn.mldoc

$(HTML_DIR)/Util/splaytree.html:	$(SRC_DIR)/Util/splaytree.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/splaytree.mldoc

$(HTML_DIR)/Util/uref.html:	$(SRC_DIR)/Util/uref.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/uref.mldoc

$(HTML_DIR)/Util/util-lib-part.html:	$(SRC_DIR)/Util/util-lib-part.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/Util/util-lib-part.mldoc

$(INFO_DIR)/HTML.info:	$(HTML_INFO_FILES)
	$(MERGE_INFO) -o $(INFO_DIR)/HTML.info $(HTML_INFO_FILES)

$(INFO_DIR)/LaTeX.info:	$(LATEX_INFO_FILES)
	$(MERGE_INFO) -o $(INFO_DIR)/LaTeX.info $(LATEX_INFO_FILES)

$(INFO_DIR)/HashCons/hash-cons.info:	$(SRC_DIR)/HashCons/hash-cons.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/HashCons/hash-cons.mldoc

$(INFO_DIR)/intro-part.info:	$(SRC_DIR)/intro-part.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/intro-part.mldoc

$(INFO_DIR)/RegExp/engine-sig.info:	$(SRC_DIR)/RegExp/engine-sig.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/engine-sig.mldoc

$(INFO_DIR)/RegExp/match-tree.info:	$(SRC_DIR)/RegExp/match-tree.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/match-tree.mldoc

$(INFO_DIR)/RegExp/parser-sig.info:	$(SRC_DIR)/RegExp/parser-sig.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/parser-sig.mldoc

$(INFO_DIR)/RegExp/regexp-fn.info:	$(SRC_DIR)/RegExp/regexp-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/regexp-fn.mldoc

$(INFO_DIR)/RegExp/regexp-intro.info:	$(SRC_DIR)/RegExp/regexp-intro.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/regexp-intro.mldoc

$(INFO_DIR)/RegExp/regexp-lib-part.info:	$(SRC_DIR)/RegExp/regexp-lib-part.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/regexp-lib-part.mldoc

$(INFO_DIR)/RegExp/regexp-sig.info:	$(SRC_DIR)/RegExp/regexp-sig.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/regexp-sig.mldoc

$(INFO_DIR)/RegExp/syntax.info:	$(SRC_DIR)/RegExp/syntax.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/RegExp/syntax.mldoc

$(INFO_DIR)/smlnj-lib.info:	$(SRC_DIR)/smlnj-lib.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/smlnj-lib.mldoc

$(INFO_DIR)/Util/array-qsort-fn.info:	$(SRC_DIR)/Util/array-qsort-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/array-qsort-fn.mldoc

$(INFO_DIR)/Util/array-qsort.info:	$(SRC_DIR)/Util/array-qsort.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/array-qsort.mldoc

$(INFO_DIR)/Util/array-sort.info:	$(SRC_DIR)/Util/array-sort.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/array-sort.mldoc

$(INFO_DIR)/Util/atom.info:	$(SRC_DIR)/Util/atom.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/atom.mldoc

$(INFO_DIR)/Util/binary-map-fn.info:	$(SRC_DIR)/Util/binary-map-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/binary-map-fn.mldoc

$(INFO_DIR)/Util/binary-set-fn.info:	$(SRC_DIR)/Util/binary-set-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/binary-set-fn.mldoc

$(INFO_DIR)/Util/bit-array.info:	$(SRC_DIR)/Util/bit-array.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/bit-array.mldoc

$(INFO_DIR)/Util/bit-vector.info:	$(SRC_DIR)/Util/bit-vector.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/bit-vector.mldoc

$(INFO_DIR)/Util/bsearch.info:	$(SRC_DIR)/Util/bsearch.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/bsearch.mldoc

$(INFO_DIR)/Util/char-map.info:	$(SRC_DIR)/Util/char-map.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/char-map.mldoc

$(INFO_DIR)/Util/dynamic-array.info:	$(SRC_DIR)/Util/dynamic-array.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/dynamic-array.mldoc

$(INFO_DIR)/Util/fifo.info:	$(SRC_DIR)/Util/fifo.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/fifo.mldoc

$(INFO_DIR)/Util/iterate.info:	$(SRC_DIR)/Util/iterate.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/iterate.mldoc

$(INFO_DIR)/Util/lib-base.info:	$(SRC_DIR)/Util/lib-base.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/lib-base.mldoc

$(INFO_DIR)/Util/list-format.info:	$(SRC_DIR)/Util/list-format.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/list-format.mldoc

$(INFO_DIR)/Util/list-map-fn.info:	$(SRC_DIR)/Util/list-map-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/list-map-fn.mldoc

$(INFO_DIR)/Util/list-set-fn.info:	$(SRC_DIR)/Util/list-set-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/list-set-fn.mldoc

$(INFO_DIR)/Util/list-xprod.info:	$(SRC_DIR)/Util/list-xprod.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/list-xprod.mldoc

$(INFO_DIR)/Util/listsort.info:	$(SRC_DIR)/Util/listsort.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/listsort.mldoc

$(INFO_DIR)/Util/mono-array-sort.info:	$(SRC_DIR)/Util/mono-array-sort.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/mono-array-sort.mldoc

$(INFO_DIR)/Util/mono-dynamic-array.info:	$(SRC_DIR)/Util/mono-dynamic-array.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/mono-dynamic-array.mldoc

$(INFO_DIR)/Util/ord-key.info:	$(SRC_DIR)/Util/ord-key.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/ord-key.mldoc

$(INFO_DIR)/Util/ord-map.info:	$(SRC_DIR)/Util/ord-map.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/ord-map.mldoc

$(INFO_DIR)/Util/ord-set.info:	$(SRC_DIR)/Util/ord-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/ord-set.mldoc

$(INFO_DIR)/Util/queue.info:	$(SRC_DIR)/Util/queue.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/queue.mldoc

$(INFO_DIR)/Util/rand.info:	$(SRC_DIR)/Util/rand.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/rand.mldoc

$(INFO_DIR)/Util/random.info:	$(SRC_DIR)/Util/random.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/random.mldoc

$(INFO_DIR)/Util/splay-map-fn.info:	$(SRC_DIR)/Util/splay-map-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/splay-map-fn.mldoc

$(INFO_DIR)/Util/splay-set-fn.info:	$(SRC_DIR)/Util/splay-set-fn.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/splay-set-fn.mldoc

$(INFO_DIR)/Util/splaytree.info:	$(SRC_DIR)/Util/splaytree.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/splaytree.mldoc

$(INFO_DIR)/Util/uref.info:	$(SRC_DIR)/Util/uref.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/uref.mldoc

$(INFO_DIR)/Util/util-lib-part.info:	$(SRC_DIR)/Util/util-lib-part.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/Util/util-lib-part.mldoc

Hardcopy:	$(LATEX_FILES)

$(LATEX_DIR)/HashCons/hash-cons.tex:	$(SRC_DIR)/HashCons/hash-cons.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/HashCons/hash-cons.mldoc

$(LATEX_DIR)/intro-part.tex:	$(SRC_DIR)/intro-part.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/intro-part.mldoc

$(LATEX_DIR)/RegExp/engine-sig.tex:	$(SRC_DIR)/RegExp/engine-sig.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/engine-sig.mldoc

$(LATEX_DIR)/RegExp/match-tree.tex:	$(SRC_DIR)/RegExp/match-tree.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/match-tree.mldoc

$(LATEX_DIR)/RegExp/parser-sig.tex:	$(SRC_DIR)/RegExp/parser-sig.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/parser-sig.mldoc

$(LATEX_DIR)/RegExp/regexp-fn.tex:	$(SRC_DIR)/RegExp/regexp-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/regexp-fn.mldoc

$(LATEX_DIR)/RegExp/regexp-intro.tex:	$(SRC_DIR)/RegExp/regexp-intro.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/regexp-intro.mldoc

$(LATEX_DIR)/RegExp/regexp-lib-part.tex:	$(SRC_DIR)/RegExp/regexp-lib-part.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/regexp-lib-part.mldoc

$(LATEX_DIR)/RegExp/regexp-sig.tex:	$(SRC_DIR)/RegExp/regexp-sig.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/regexp-sig.mldoc

$(LATEX_DIR)/RegExp/syntax.tex:	$(SRC_DIR)/RegExp/syntax.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/RegExp/syntax.mldoc

$(LATEX_DIR)/smlnj-lib.tex:	$(SRC_DIR)/smlnj-lib.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/smlnj-lib.mldoc

$(LATEX_DIR)/Util/array-qsort-fn.tex:	$(SRC_DIR)/Util/array-qsort-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/array-qsort-fn.mldoc

$(LATEX_DIR)/Util/array-qsort.tex:	$(SRC_DIR)/Util/array-qsort.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/array-qsort.mldoc

$(LATEX_DIR)/Util/array-sort.tex:	$(SRC_DIR)/Util/array-sort.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/array-sort.mldoc

$(LATEX_DIR)/Util/atom.tex:	$(SRC_DIR)/Util/atom.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/atom.mldoc

$(LATEX_DIR)/Util/binary-map-fn.tex:	$(SRC_DIR)/Util/binary-map-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/binary-map-fn.mldoc

$(LATEX_DIR)/Util/binary-set-fn.tex:	$(SRC_DIR)/Util/binary-set-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/binary-set-fn.mldoc

$(LATEX_DIR)/Util/bit-array.tex:	$(SRC_DIR)/Util/bit-array.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/bit-array.mldoc

$(LATEX_DIR)/Util/bit-vector.tex:	$(SRC_DIR)/Util/bit-vector.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/bit-vector.mldoc

$(LATEX_DIR)/Util/bsearch.tex:	$(SRC_DIR)/Util/bsearch.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/bsearch.mldoc

$(LATEX_DIR)/Util/char-map.tex:	$(SRC_DIR)/Util/char-map.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/char-map.mldoc

$(LATEX_DIR)/Util/dynamic-array.tex:	$(SRC_DIR)/Util/dynamic-array.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/dynamic-array.mldoc

$(LATEX_DIR)/Util/fifo.tex:	$(SRC_DIR)/Util/fifo.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/fifo.mldoc

$(LATEX_DIR)/Util/iterate.tex:	$(SRC_DIR)/Util/iterate.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/iterate.mldoc

$(LATEX_DIR)/Util/lib-base.tex:	$(SRC_DIR)/Util/lib-base.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/lib-base.mldoc

$(LATEX_DIR)/Util/list-format.tex:	$(SRC_DIR)/Util/list-format.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/list-format.mldoc

$(LATEX_DIR)/Util/list-map-fn.tex:	$(SRC_DIR)/Util/list-map-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/list-map-fn.mldoc

$(LATEX_DIR)/Util/list-set-fn.tex:	$(SRC_DIR)/Util/list-set-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/list-set-fn.mldoc

$(LATEX_DIR)/Util/list-xprod.tex:	$(SRC_DIR)/Util/list-xprod.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/list-xprod.mldoc

$(LATEX_DIR)/Util/listsort.tex:	$(SRC_DIR)/Util/listsort.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/listsort.mldoc

$(LATEX_DIR)/Util/mono-array-sort.tex:	$(SRC_DIR)/Util/mono-array-sort.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/mono-array-sort.mldoc

$(LATEX_DIR)/Util/mono-dynamic-array.tex:	$(SRC_DIR)/Util/mono-dynamic-array.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/mono-dynamic-array.mldoc

$(LATEX_DIR)/Util/ord-key.tex:	$(SRC_DIR)/Util/ord-key.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/ord-key.mldoc

$(LATEX_DIR)/Util/ord-map.tex:	$(SRC_DIR)/Util/ord-map.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/ord-map.mldoc

$(LATEX_DIR)/Util/ord-set.tex:	$(SRC_DIR)/Util/ord-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/ord-set.mldoc

$(LATEX_DIR)/Util/queue.tex:	$(SRC_DIR)/Util/queue.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/queue.mldoc

$(LATEX_DIR)/Util/rand.tex:	$(SRC_DIR)/Util/rand.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/rand.mldoc

$(LATEX_DIR)/Util/random.tex:	$(SRC_DIR)/Util/random.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/random.mldoc

$(LATEX_DIR)/Util/splay-map-fn.tex:	$(SRC_DIR)/Util/splay-map-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/splay-map-fn.mldoc

$(LATEX_DIR)/Util/splay-set-fn.tex:	$(SRC_DIR)/Util/splay-set-fn.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/splay-set-fn.mldoc

$(LATEX_DIR)/Util/splaytree.tex:	$(SRC_DIR)/Util/splaytree.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/splaytree.mldoc

$(LATEX_DIR)/Util/uref.tex:	$(SRC_DIR)/Util/uref.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/uref.mldoc

$(LATEX_DIR)/Util/util-lib-part.tex:	$(SRC_DIR)/Util/util-lib-part.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/Util/util-lib-part.mldoc

Proof:	$(PROOF_FILES)

$(PROOF_DIR)/HashCons/hash-cons.tex:	$(SRC_DIR)/HashCons/hash-cons.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/HashCons/hash-cons.mldoc

$(PROOF_DIR)/intro-part.tex:	$(SRC_DIR)/intro-part.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/intro-part.mldoc

$(PROOF_DIR)/RegExp/engine-sig.tex:	$(SRC_DIR)/RegExp/engine-sig.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/engine-sig.mldoc

$(PROOF_DIR)/RegExp/match-tree.tex:	$(SRC_DIR)/RegExp/match-tree.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/match-tree.mldoc

$(PROOF_DIR)/RegExp/parser-sig.tex:	$(SRC_DIR)/RegExp/parser-sig.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/parser-sig.mldoc

$(PROOF_DIR)/RegExp/regexp-fn.tex:	$(SRC_DIR)/RegExp/regexp-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/regexp-fn.mldoc

$(PROOF_DIR)/RegExp/regexp-intro.tex:	$(SRC_DIR)/RegExp/regexp-intro.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/regexp-intro.mldoc

$(PROOF_DIR)/RegExp/regexp-lib-part.tex:	$(SRC_DIR)/RegExp/regexp-lib-part.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/regexp-lib-part.mldoc

$(PROOF_DIR)/RegExp/regexp-sig.tex:	$(SRC_DIR)/RegExp/regexp-sig.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/regexp-sig.mldoc

$(PROOF_DIR)/RegExp/syntax.tex:	$(SRC_DIR)/RegExp/syntax.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/RegExp/syntax.mldoc

$(PROOF_DIR)/smlnj-lib.tex:	$(SRC_DIR)/smlnj-lib.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/smlnj-lib.mldoc

$(PROOF_DIR)/Util/array-qsort-fn.tex:	$(SRC_DIR)/Util/array-qsort-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/array-qsort-fn.mldoc

$(PROOF_DIR)/Util/array-qsort.tex:	$(SRC_DIR)/Util/array-qsort.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/array-qsort.mldoc

$(PROOF_DIR)/Util/array-sort.tex:	$(SRC_DIR)/Util/array-sort.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/array-sort.mldoc

$(PROOF_DIR)/Util/atom.tex:	$(SRC_DIR)/Util/atom.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/atom.mldoc

$(PROOF_DIR)/Util/binary-map-fn.tex:	$(SRC_DIR)/Util/binary-map-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/binary-map-fn.mldoc

$(PROOF_DIR)/Util/binary-set-fn.tex:	$(SRC_DIR)/Util/binary-set-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/binary-set-fn.mldoc

$(PROOF_DIR)/Util/bit-array.tex:	$(SRC_DIR)/Util/bit-array.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/bit-array.mldoc

$(PROOF_DIR)/Util/bit-vector.tex:	$(SRC_DIR)/Util/bit-vector.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/bit-vector.mldoc

$(PROOF_DIR)/Util/bsearch.tex:	$(SRC_DIR)/Util/bsearch.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/bsearch.mldoc

$(PROOF_DIR)/Util/char-map.tex:	$(SRC_DIR)/Util/char-map.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/char-map.mldoc

$(PROOF_DIR)/Util/dynamic-array.tex:	$(SRC_DIR)/Util/dynamic-array.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/dynamic-array.mldoc

$(PROOF_DIR)/Util/fifo.tex:	$(SRC_DIR)/Util/fifo.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/fifo.mldoc

$(PROOF_DIR)/Util/iterate.tex:	$(SRC_DIR)/Util/iterate.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/iterate.mldoc

$(PROOF_DIR)/Util/lib-base.tex:	$(SRC_DIR)/Util/lib-base.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/lib-base.mldoc

$(PROOF_DIR)/Util/list-format.tex:	$(SRC_DIR)/Util/list-format.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/list-format.mldoc

$(PROOF_DIR)/Util/list-map-fn.tex:	$(SRC_DIR)/Util/list-map-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/list-map-fn.mldoc

$(PROOF_DIR)/Util/list-set-fn.tex:	$(SRC_DIR)/Util/list-set-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/list-set-fn.mldoc

$(PROOF_DIR)/Util/list-xprod.tex:	$(SRC_DIR)/Util/list-xprod.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/list-xprod.mldoc

$(PROOF_DIR)/Util/listsort.tex:	$(SRC_DIR)/Util/listsort.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/listsort.mldoc

$(PROOF_DIR)/Util/mono-array-sort.tex:	$(SRC_DIR)/Util/mono-array-sort.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/mono-array-sort.mldoc

$(PROOF_DIR)/Util/mono-dynamic-array.tex:	$(SRC_DIR)/Util/mono-dynamic-array.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/mono-dynamic-array.mldoc

$(PROOF_DIR)/Util/ord-key.tex:	$(SRC_DIR)/Util/ord-key.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/ord-key.mldoc

$(PROOF_DIR)/Util/ord-map.tex:	$(SRC_DIR)/Util/ord-map.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/ord-map.mldoc

$(PROOF_DIR)/Util/ord-set.tex:	$(SRC_DIR)/Util/ord-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/ord-set.mldoc

$(PROOF_DIR)/Util/queue.tex:	$(SRC_DIR)/Util/queue.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/queue.mldoc

$(PROOF_DIR)/Util/rand.tex:	$(SRC_DIR)/Util/rand.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/rand.mldoc

$(PROOF_DIR)/Util/random.tex:	$(SRC_DIR)/Util/random.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/random.mldoc

$(PROOF_DIR)/Util/splay-map-fn.tex:	$(SRC_DIR)/Util/splay-map-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/splay-map-fn.mldoc

$(PROOF_DIR)/Util/splay-set-fn.tex:	$(SRC_DIR)/Util/splay-set-fn.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/splay-set-fn.mldoc

$(PROOF_DIR)/Util/splaytree.tex:	$(SRC_DIR)/Util/splaytree.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/splaytree.mldoc

$(PROOF_DIR)/Util/uref.tex:	$(SRC_DIR)/Util/uref.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/uref.mldoc

$(PROOF_DIR)/Util/util-lib-part.tex:	$(SRC_DIR)/Util/util-lib-part.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/Util/util-lib-part.mldoc

clean-info:
	rm -f $(INFO_DIR)/*.info

clean-latex:
	rm -f $(LATEX_FILES)
	rm -f $(LATEX_DIR)/*.aux
	rm -f $(LATEX_DIR)/*.bbl
	rm -f $(LATEX_DIR)/*.blg
	rm -f $(LATEX_DIR)/*.dvi
	rm -f $(LATEX_DIR)/*.idx
	rm -f $(LATEX_DIR)/*.ilg
	rm -f $(LATEX_DIR)/*.ind
	rm -f $(LATEX_DIR)/*.rnd
	rm -f $(LATEX_DIR)/*.nnd
	rm -f $(LATEX_DIR)/*.log
	rm -f $(LATEX_DIR)/*.ps
	rm -f $(LATEX_DIR)/*.pdf
	rm -f $(LATEX_DIR)/*.toc

clean-proof:
	rm -f $(PROOF_FILES)
	rm -f $(PROOF_DIR)/*.aux
	rm -f $(PROOF_DIR)/*.bbl
	rm -f $(PROOF_DIR)/*.blg
	rm -f $(PROOF_DIR)/*.dvi
	rm -f $(PROOF_DIR)/*.idx
	rm -f $(PROOF_DIR)/*.ilg
	rm -f $(PROOF_DIR)/*.ind
	rm -f $(PROOF_DIR)/*.rnd
	rm -f $(PROOF_DIR)/*.nnd
	rm -f $(PROOF_DIR)/*.log
	rm -f $(PROOF_DIR)/*.ps
	rm -f $(PROOF_DIR)/*.pdf
	rm -f $(PROOF_DIR)/*.toc

clean-html:
	rm -f $(HTML_FILES)

clean:	clean-html clean-info clean-latex clean-proof

