(* sml-basis-unix.idl
 *
 * COPYRIGHT (c) 2008 The Fellowship of SML/NJ (http://www.smlnj.org)
 * All rights reserved.
 *
 * The IDL spec to support the Unix module of the SML Basis Library.
 *)

sml_structure ("SMLBasisUnix");
sml_signature ("SML_BASIS_UNIX");
clib_name ("SMLBasisUnix");

(*
execute
wait
kill
exit
*)
