#!/bin/sh
#
# build script for ml-lex under the new runtime system.
#
# options:
#   -arch arch		-- specify the architecture, "heap" is the default.
#   -o image		-- specify the name of the heap image, "ml-lex.ARCH"
#			   is the default.
#   -sml path		-- specify the path to the sml executable, "../../bin/sml"
#			   is the default.

CMD="build"

ROOT="ml-lex"
HEAP_IMAGE=""
ARCH="heap"
BIN="../../bin"
SML="$BIN/sml"

#
# determine the host architecture
#
ARCH_N_OPSYS=`$BIN/.arch-n-opsys`
if [ $? != "0" ]; then
  echo "$CMD: unable to determine architecture/operating system"
  exit 1
fi
eval $ARCH_N_OPSYS

#
# process command-line options
#
ARGS=""
while [ "$#" != "0" ]
do
    arg=$1
    shift
    case $arg in
	-arch)
	    if [ "$#" = "0" ]; then
		echo "$CMD: must supply architecture for -arch option"
		exit 1
	    fi
	    ARCH=$1; shift
	;;
	-o)
	    if [ "$#" = "0" ]; then
		echo "$CMD: must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	;;
	-sml)
	    if [ "$#" = "0" ]; then
		echo "$CMD: must supply path for -sml option"
		exit 1
	    fi
	    SML=$1; shift
	;;
	*)
	    ARGS="$ARGS $arg"
	;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$ROOT"
fi

$SML $ARGS <<ZZZ
  use "lexgen.sml";
  use "export-lex.sml";
  export "$HEAP_IMAGE" : unit;
ZZZ

