(*
 * WARNING: This file was automatically generated by MDLGen (v3.0)
 * from the machine description file "alpha/alpha.mdl".
 * DO NOT EDIT this file directly
 *)


signature ALPHAINSTR =
sig
   structure C : ALPHACELLS
   structure Constant: CONSTANT
   structure LabelExp: LABELEXP
   structure Region : REGION
      sharing Constant = LabelExp.Constant
   datatype ea =
     Direct of C.cell
   | FDirect of C.cell
   | Displace of {base:C.cell, disp:int}
   datatype operand =
     REGop of C.cell
   | IMMop of int
   | HILABop of LabelExp.labexp
   | LOLABop of LabelExp.labexp
   | LABop of LabelExp.labexp
   datatype branch =
     BR
   | BLBC
   | BEQ
   | BLT
   | BLE
   | BLBS
   | BNE
   | BGE
   | BGT
   datatype fbranch =
     FBEQ
   | FBLT
   | FBLE
   | FBNE
   | FBGE
   | FBGT
   datatype load =
     LDB
   | LDW
   | LDBU
   | LDWU
   | LDL
   | LDL_L
   | LDQ
   | LDQ_L
   | LDQ_U
   datatype store =
     STB
   | STW
   | STL
   | STQ
   | STQ_U
   datatype fload =
     LDF
   | LDG
   | LDS
   | LDT
   datatype fstore =
     STF
   | STG
   | STS
   | STT
   datatype operate =
     ADDL
   | ADDQ
   | CMPBGE
   | CMPEQ
   | CMPLE
   | CMPLT
   | CMPULE
   | CMPULT
   | SUBL
   | SUBQ
   | S4ADDL
   | S4ADDQ
   | S4SUBL
   | S4SUBQ
   | S8ADDL
   | S8ADDQ
   | S8SUBL
   | S8SUBQ
   | AND
   | BIC
   | BIS
   | EQV
   | ORNOT
   | XOR
   | EXTBL
   | EXTLH
   | EXTLL
   | EXTQH
   | EXTQL
   | EXTWH
   | EXTWL
   | INSBL
   | INSLH
   | INSLL
   | INSQH
   | INSQL
   | INSWH
   | INSWL
   | MSKBL
   | MSKLH
   | MSKLL
   | MSKQH
   | MSKQL
   | MSKWH
   | MSKWL
   | SLL
   | SRA
   | SRL
   | ZAP
   | ZAPNOT
   | MULL
   | MULQ
   | UMULH
   datatype cmove =
     CMOVEQ
   | CMOVLBC
   | CMOVLBS
   | CMOVGE
   | CMOVGT
   | CMOVLE
   | CMOVLT
   | CMOVNE
   datatype pseudo_op =
     DIVL
   | DIVLU
   | DIVQ
   | DIVQU
   | REML
   | REMLU
   | REMQ
   | REMQU
   datatype operateV =
     ADDLV
   | ADDQV
   | SUBLV
   | SUBQV
   | MULLV
   | MULQV
   datatype funary =
     CVTLQ
   | CVTQL
   | CVTQLSV
   | CVTQLV
   | CVTQS
   | CVTQSC
   | CVTQT
   | CVTQTC
   | CVTTS
   | CVTTSC
   | CVTST
   | CVTSTS
   | CVTTQ
   | CVTTQC
   datatype foperate =
     CPYS
   | CPYSE
   | CPYSN
   | MF_FPCR
   | MT_FPCR
   | CMPTEQ
   | CMPTLT
   | CMPTLE
   | CMPTUN
   | CMPTEQSU
   | CMPTLTSU
   | CMPTLESU
   | CMPTUNSU
   | ADDS
   | ADDT
   | DIVS
   | DIVT
   | MULS
   | MULT
   | SUBS
   | SUBT
   datatype fcmove =
     FCMOVEQ
   | FCMOVGE
   | FCMOVGT
   | FCMOVLE
   | FCMOVLT
   | FCMOVNE
   datatype foperateV =
     ADDSSUD
   | ADDSSU
   | ADDTSUD
   | ADDTSU
   | DIVSSUD
   | DIVSSU
   | DIVTSUD
   | DIVTSU
   | MULSSUD
   | MULSSU
   | MULTSUD
   | MULTSU
   | SUBSSUD
   | SUBSSU
   | SUBTSUD
   | SUBTSU
   datatype osf_user_palcode =
     BPT
   | BUGCHK
   | CALLSYS
   | GENTRAP
   | IMB
   | RDUNIQUE
   | WRUNIQUE
   type addressing_mode = (C.cell * operand)
   datatype instruction =
     DEFFREG of C.cell
   | LDA of {r:C.cell, b:C.cell, d:operand}
   | LDAH of {r:C.cell, b:C.cell, d:operand}
   | LOAD of {ldOp:load, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | STORE of {stOp:store, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | FLOAD of {ldOp:fload, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | FSTORE of {stOp:fstore, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | JMPL of ({r:C.cell, b:C.cell, d:int} * Label.label list)
   | JSR of {r:C.cell, b:C.cell, d:int, defs:C.cellset, uses:C.cellset, mem:Region.region}
   | BSR of {r:C.cell, lab:Label.label, defs:C.cellset, uses:C.cellset, mem:Region.region}
   | RET of {r:C.cell, b:C.cell, d:int}
   | BRANCH of {b:branch, r:C.cell, lab:Label.label}
   | FBRANCH of {b:fbranch, f:C.cell, lab:Label.label}
   | OPERATE of {oper:operate, ra:C.cell, rb:operand, rc:C.cell}
   | OPERATEV of {oper:operateV, ra:C.cell, rb:operand, rc:C.cell}
   | CMOVE of {oper:cmove, ra:C.cell, rb:operand, rc:C.cell}
   | PSEUDOARITH of {oper:pseudo_op, ra:C.cell, rb:operand, rc:C.cell, tmps:C.cellset}
   | COPY of {dst:C.cell list, src:C.cell list, impl:instruction list option ref, 
        tmp:ea option}
   | FCOPY of {dst:C.cell list, src:C.cell list, impl:instruction list option ref, 
        tmp:ea option}
   | FUNARY of {oper:funary, fb:C.cell, fc:C.cell}
   | FOPERATE of {oper:foperate, fa:C.cell, fb:C.cell, fc:C.cell}
   | FOPERATEV of {oper:foperateV, fa:C.cell, fb:C.cell, fc:C.cell}
   | FCMOVE of {oper:fcmove, fa:C.cell, fb:C.cell, fc:C.cell}
   | TRAPB
   | CALL_PAL of {code:osf_user_palcode, def:C.cellset, use:C.cellset}
   | ANNOTATION of {i:instruction, a:Annotations.annotation}
   | SOURCE of {}
   | SINK of {}
   | PHI of {}
end

functor AlphaInstr(structure LabelExp : LABELEXP
                   structure Region   : REGION
                  ) : ALPHAINSTR =
struct
   structure C = AlphaCells
   structure Region = Region
   structure LabelExp = LabelExp
   structure Constant = LabelExp.Constant
   datatype ea =
     Direct of C.cell
   | FDirect of C.cell
   | Displace of {base:C.cell, disp:int}
   datatype operand =
     REGop of C.cell
   | IMMop of int
   | HILABop of LabelExp.labexp
   | LOLABop of LabelExp.labexp
   | LABop of LabelExp.labexp
   datatype branch =
     BR
   | BLBC
   | BEQ
   | BLT
   | BLE
   | BLBS
   | BNE
   | BGE
   | BGT
   datatype fbranch =
     FBEQ
   | FBLT
   | FBLE
   | FBNE
   | FBGE
   | FBGT
   datatype load =
     LDB
   | LDW
   | LDBU
   | LDWU
   | LDL
   | LDL_L
   | LDQ
   | LDQ_L
   | LDQ_U
   datatype store =
     STB
   | STW
   | STL
   | STQ
   | STQ_U
   datatype fload =
     LDF
   | LDG
   | LDS
   | LDT
   datatype fstore =
     STF
   | STG
   | STS
   | STT
   datatype operate =
     ADDL
   | ADDQ
   | CMPBGE
   | CMPEQ
   | CMPLE
   | CMPLT
   | CMPULE
   | CMPULT
   | SUBL
   | SUBQ
   | S4ADDL
   | S4ADDQ
   | S4SUBL
   | S4SUBQ
   | S8ADDL
   | S8ADDQ
   | S8SUBL
   | S8SUBQ
   | AND
   | BIC
   | BIS
   | EQV
   | ORNOT
   | XOR
   | EXTBL
   | EXTLH
   | EXTLL
   | EXTQH
   | EXTQL
   | EXTWH
   | EXTWL
   | INSBL
   | INSLH
   | INSLL
   | INSQH
   | INSQL
   | INSWH
   | INSWL
   | MSKBL
   | MSKLH
   | MSKLL
   | MSKQH
   | MSKQL
   | MSKWH
   | MSKWL
   | SLL
   | SRA
   | SRL
   | ZAP
   | ZAPNOT
   | MULL
   | MULQ
   | UMULH
   datatype cmove =
     CMOVEQ
   | CMOVLBC
   | CMOVLBS
   | CMOVGE
   | CMOVGT
   | CMOVLE
   | CMOVLT
   | CMOVNE
   datatype pseudo_op =
     DIVL
   | DIVLU
   | DIVQ
   | DIVQU
   | REML
   | REMLU
   | REMQ
   | REMQU
   datatype operateV =
     ADDLV
   | ADDQV
   | SUBLV
   | SUBQV
   | MULLV
   | MULQV
   datatype funary =
     CVTLQ
   | CVTQL
   | CVTQLSV
   | CVTQLV
   | CVTQS
   | CVTQSC
   | CVTQT
   | CVTQTC
   | CVTTS
   | CVTTSC
   | CVTST
   | CVTSTS
   | CVTTQ
   | CVTTQC
   datatype foperate =
     CPYS
   | CPYSE
   | CPYSN
   | MF_FPCR
   | MT_FPCR
   | CMPTEQ
   | CMPTLT
   | CMPTLE
   | CMPTUN
   | CMPTEQSU
   | CMPTLTSU
   | CMPTLESU
   | CMPTUNSU
   | ADDS
   | ADDT
   | DIVS
   | DIVT
   | MULS
   | MULT
   | SUBS
   | SUBT
   datatype fcmove =
     FCMOVEQ
   | FCMOVGE
   | FCMOVGT
   | FCMOVLE
   | FCMOVLT
   | FCMOVNE
   datatype foperateV =
     ADDSSUD
   | ADDSSU
   | ADDTSUD
   | ADDTSU
   | DIVSSUD
   | DIVSSU
   | DIVTSUD
   | DIVTSU
   | MULSSUD
   | MULSSU
   | MULTSUD
   | MULTSU
   | SUBSSUD
   | SUBSSU
   | SUBTSUD
   | SUBTSU
   datatype osf_user_palcode =
     BPT
   | BUGCHK
   | CALLSYS
   | GENTRAP
   | IMB
   | RDUNIQUE
   | WRUNIQUE
   type addressing_mode = (C.cell * operand)
   datatype instruction =
     DEFFREG of C.cell
   | LDA of {r:C.cell, b:C.cell, d:operand}
   | LDAH of {r:C.cell, b:C.cell, d:operand}
   | LOAD of {ldOp:load, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | STORE of {stOp:store, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | FLOAD of {ldOp:fload, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | FSTORE of {stOp:fstore, r:C.cell, b:C.cell, d:operand, mem:Region.region}
   | JMPL of ({r:C.cell, b:C.cell, d:int} * Label.label list)
   | JSR of {r:C.cell, b:C.cell, d:int, defs:C.cellset, uses:C.cellset, mem:Region.region}
   | BSR of {r:C.cell, lab:Label.label, defs:C.cellset, uses:C.cellset, mem:Region.region}
   | RET of {r:C.cell, b:C.cell, d:int}
   | BRANCH of {b:branch, r:C.cell, lab:Label.label}
   | FBRANCH of {b:fbranch, f:C.cell, lab:Label.label}
   | OPERATE of {oper:operate, ra:C.cell, rb:operand, rc:C.cell}
   | OPERATEV of {oper:operateV, ra:C.cell, rb:operand, rc:C.cell}
   | CMOVE of {oper:cmove, ra:C.cell, rb:operand, rc:C.cell}
   | PSEUDOARITH of {oper:pseudo_op, ra:C.cell, rb:operand, rc:C.cell, tmps:C.cellset}
   | COPY of {dst:C.cell list, src:C.cell list, impl:instruction list option ref, 
        tmp:ea option}
   | FCOPY of {dst:C.cell list, src:C.cell list, impl:instruction list option ref, 
        tmp:ea option}
   | FUNARY of {oper:funary, fb:C.cell, fc:C.cell}
   | FOPERATE of {oper:foperate, fa:C.cell, fb:C.cell, fc:C.cell}
   | FOPERATEV of {oper:foperateV, fa:C.cell, fb:C.cell, fc:C.cell}
   | FCMOVE of {oper:fcmove, fa:C.cell, fb:C.cell, fc:C.cell}
   | TRAPB
   | CALL_PAL of {code:osf_user_palcode, def:C.cellset, use:C.cellset}
   | ANNOTATION of {i:instruction, a:Annotations.annotation}
   | SOURCE of {}
   | SINK of {}
   | PHI of {}
end

