(*
 * This file was automatically generated by MDGen
 * from the machine description file "alpha/alpha.md".
 *)


signature ALPHACELLS =
sig
   datatype mycellkind =
     UNKNOWN
   | MEM
   | CTRL
   | CC
   | GP
   | FP
   withtype cellset = (int list * int list)
   include CELLS_BASIS where type cellkind = mycellkind
   val showCC : register -> string
   val showGP : register -> string
   val showFP : register -> string
   val newCC : unit -> register
   val newGP : unit -> register
   val newFP : unit -> register
   val addGP : (register * cellset) -> cellset
   val addFP : (register * cellset) -> cellset
   val asmTmpR : register
   val stackptrR : register
   val fasmTmp : register
   val zeroReg : cellkind -> register option
   val toString : cellkind -> register -> string
   val addCell : cellkind -> register * cellset -> cellset
   val addReg : register * cellset -> cellset
   val addFreg : register * cellset -> cellset
   val getCell : cellkind -> cellset -> register list
   val updateCell : cellkind -> cellset * register list -> cellset
   val empty : cellset
   val cellsetToString : cellset -> string
   val cellsetToString' : (register -> register) -> cellset -> string
   val cellsetToRegs : cellset -> register list
end

structure AlphaCells : ALPHACELLS =
struct
   datatype mycellkind =
     UNKNOWN
   | MEM
   | CTRL
   | CC
   | GP
   | FP
   withtype cellset = (int list * int list)
   exception AlphaCells
   structure SL = SortedList
   fun error msg = MLRiscErrorMsg.error("AlphaCells",msg)
   val cellkindToString = (fn CC => "CC"
                            | GP => "GP"
                            | FP => "FP"
                            | MEM => "MEM"
                            | CTRL => "CTRL"
                            | UNKNOWN => "UNKNOWN"
                          )
   structure MyCellsBasis = CellsBasisFn
      (type cellkind = mycellkind
       exception Cells = AlphaCells
       val unknown = UNKNOWN
       val cellkindToString = cellkindToString
       val INT = GP
       val FLOAT = FP
       val firstPseudo = 256
       val kinds = [CC, GP, FP, MEM, CTRL]
       val physical = [{from=64, to=0, kind=CC}, {from=0, to=31, kind=GP}, {from=32, to=63, kind=FP}]
      )

   open MyCellsBasis
   val offsetCC = 64
  and offsetGP = 0
  and offsetFP = 32
  and newCC = (newCell CC)
  and newGP = (newCell GP)
  and newFP = (newCell FP)
  and cellnames = ["CC", "GP", "FP"]
  and cellsetnames = ["GP", "FP"]
   val asmTmpR = (28 + offsetGP)
   val stackptrR = (30 + offsetGP)
   val fasmTmp = (30 + offsetFP)

   fun showCC r = let
          val r = (if (r <= 0)
                then (r - 64)
                else r)
       in ((fn _ => "cc"
           ) r)
       end

   and showGP r = ((fn 30 => "$sp"
                     | r => ("$" ^ (Int.toString r))
                   ) r)
   and showFP r = let
          val r = (if (r <= 63)
                then (r - 32)
                else r)
       in ((fn f => ("$f" ^ (Int.toString f))
           ) r)
       end

   and toString CC = showCC
     | toString GP = showGP
     | toString FP = showFP
     | toString MEM = (fn r => ("m" ^ (Int.toString r))
                      )
     | toString CTRL = (fn r => ("ctrl" ^ (Int.toString r))
                       )
     | toString UNKNOWN = (fn r => ("unknown" ^ (Int.toString r))
                          )
   val empty = ([], [])

   fun addCell CC = addGP
     | addCell GP = addGP
     | addCell FP = addFP
     | addCell _ = (error "addCell")
   and getCell GP = getCellGP
     | getCell FP = getCellFP
     | getCell _ = (error "getCell")
   and updateCell GP = updateCellGP
     | updateCell FP = updateCellFP
     | updateCell _ = (error "updateCell")
   and addGP (r, (setGP, setFP)) = ((SL.enter (r, setGP)), setFP)
   and addFP (r, (setGP, setFP)) = (setGP, (SL.enter (r, setFP)))
   and getCellGP (setGP, setFP) = setGP
   and getCellFP (setGP, setFP) = setFP
   and updateCellGP ((setGP, setFP), r) = (r, setFP)
   and updateCellFP ((setGP, setFP), r) = (setGP, r)
   and cellsetToString (setGP, setFP) = (printTuple (cellsetnames, [((printSet showGP) setGP), ((printSet showFP) setFP)]))
   and cellsetToString' regmap = (fn (setGP, setFP) => (printTuple (cellsetnames, [((printSet showGP) ((map regmap) setGP)), ((printSet showFP) ((map regmap) setFP))]))
                                 )
   and cellsetToRegs (setGP, setFP) = (setGP @ setFP)
   val addReg = addGP
   val addFreg = addFP

   fun zeroReg GP = (SOME (31 + offsetGP))
     | zeroReg FP = (SOME (31 + offsetFP))
     | zeroReg _ = NONE
end

