PACKAGE = sml-mode
ELFILES	= sml-compat.el sml-util.el sml-defs.el sml-move.el sml-mode.el \
	sml-proc.el

default: elcfiles

TESTCASE = testcases.sml

test:
	$(RM) $(TESTCASE).new
	$(EMACS) -batch $(TESTCASE) \
	    --eval '(indent-region (point-min) (point-max) nil)' \
	    --eval '(write-region (point-min) (point-max) "$(TESTCASE).new")'
	diff -u $(TESTCASE) $(TESTCASE).new
