#!/bin/sh

if [ $# -gt 0 ] ; then
    HEAP_IMAGE=$1
    shift
else
    HEAP_IMAGE=sml
fi

cmddir=`dirname $0`
cmddir=`cd $cmddir; pwd`

bin=../../bin
[ -x "$bin/.arch-n-opsys" ] || bin="$cmddir/$bin"

eval `$bin/.arch-n-opsys`

heapdir=`dirname $HEAP_IMAGE`
[ -f "$heapdir/$HEAP_IMAGE.$HEAP_SUFFIX" ] || heapdir="$cmddir/$heapdir"
HEAP_IMAGE=`cd $heapdir; pwd`/$HEAP_IMAGE

LIB_DIR=${HEAP_IMAGE}.lib

CM_PATHCONFIG=$LIB_DIR/pathconfig CM_LOCAL_PATHCONFIG=/dev/null \
    $bin/sml @SMLload=$HEAP_IMAGE "$@"
