signature ASSERT =
sig
    (* Turns on recognition of `assert' keyword. 
     * default: false
     *)
    val enable : bool ref  

    (* Remove assertions from object code.
     * default: false
     *)
    val ignore : bool ref

    (* Information about the assertion.  For now this is just
     * a string describing the region of code in which the assert
     * failed; e.g., "foo.sml:7.18-7.25".  
     *)
    type auxinfo = string

    (* This exception is thrown when an assertion fails. *)
    exception Assert of auxinfo

    (* Customize handling of failed assertions.  The default
     * handler prints a useful message to TextIO.stdErr and 
     * raises Assert.  
     *)
    val handler : (auxinfo -> unit) option -> auxinfo -> unit

    (* A call to this is generated by `elabcore.sml' when an assertion
     * condition fails (assuming `enable' and `ignore', above, are
     * both true).  It just calls the current handler.
     *)
    val fail : auxinfo -> unit
end
