/* 
 * 
 * This file is GENERATED by the varargs library. Modify the
 * code at your peril :).
 * 
 * This interpreter parses the arguments for a vararg C function,
 * putting them in the correct locations, and then calls the function.
 * 
 * Mike Rainey (mrainey@cs.uchicago.edu)
 */
	.text
_VarargInterp:
	/* live= GP={%edi %esi %ebx} spilled=  */
	pushl	%ebp
	movl	%esp, %ebp
	movl	12(%ebp), %ecx
	subl	$4088, %esp
	jmp	interpEntry96
interp97:
	addl	$32, %ecx
interpEntry96:
	cmpl	16(%ebp), %ecx
	jge	gotoC98
entry1:
	cmpl	$0, (%ecx)
	je	kind-GPR2
	cmpl	$1, (%ecx)
	je	kind-FPR3
	cmpl	$2, (%ecx)
	je	kind-STK4
	cmpl	$3, (%ecx)
	je	kind-FSTK5
	jmp	_error
kind-GPR2:
	cmpl	$8, 4(%ecx)
	je	width-GPR-86
	cmpl	$16, 4(%ecx)
	je	width-GPR-167
	cmpl	$32, 4(%ecx)
	je	width-GPR-328
	cmpl	$64, 4(%ecx)
	je	width-GPR-649
	jmp	_error
kind-FPR3:
	cmpl	$8, 4(%ecx)
	je	width-FPR-8A
	cmpl	$16, 4(%ecx)
	je	width-FPR-16B
	cmpl	$32, 4(%ecx)
	je	width-FPR-32C
	cmpl	$64, 4(%ecx)
	je	width-FPR-64D
	jmp	_error
kind-STK4:
	cmpl	$8, 4(%ecx)
	je	width-STK-8E
	cmpl	$16, 4(%ecx)
	je	width-STK-16F
	cmpl	$32, 4(%ecx)
	je	width-STK-3210
	cmpl	$64, 4(%ecx)
	je	width-STK-6411
	jmp	_error
kind-FSTK5:
	cmpl	$8, 4(%ecx)
	je	width-FSTK-812
	cmpl	$16, 4(%ecx)
	je	width-FSTK-1613
	cmpl	$32, 4(%ecx)
	je	width-FSTK-3214
	cmpl	$64, 4(%ecx)
	je	width-FSTK-6415
	jmp	_error
width-GPR-86:
	cmpl	$8, 8(%ecx)
	je	narrowing-GPR-8-816
	cmpl	$16, 8(%ecx)
	je	narrowing-GPR-8-1617
	cmpl	$32, 8(%ecx)
	je	narrowing-GPR-8-3218
	cmpl	$64, 8(%ecx)
	je	narrowing-GPR-8-6419
	jmp	_error
width-GPR-167:
	cmpl	$8, 8(%ecx)
	je	narrowing-GPR-16-81A
	cmpl	$16, 8(%ecx)
	je	narrowing-GPR-16-161B
	cmpl	$32, 8(%ecx)
	je	narrowing-GPR-16-321C
	cmpl	$64, 8(%ecx)
	je	narrowing-GPR-16-641D
	jmp	_error
width-GPR-328:
	cmpl	$8, 8(%ecx)
	je	narrowing-GPR-32-81E
	cmpl	$16, 8(%ecx)
	je	narrowing-GPR-32-161F
	cmpl	$32, 8(%ecx)
	je	narrowing-GPR-32-3220
	cmpl	$64, 8(%ecx)
	je	narrowing-GPR-32-6421
	jmp	_error
width-GPR-649:
	cmpl	$8, 8(%ecx)
	je	narrowing-GPR-64-822
	cmpl	$16, 8(%ecx)
	je	narrowing-GPR-64-1623
	cmpl	$32, 8(%ecx)
	je	narrowing-GPR-64-3224
	cmpl	$64, 8(%ecx)
	je	narrowing-GPR-64-6425
	jmp	_error
width-FPR-8A:
	cmpl	$8, 8(%ecx)
	je	narrowing-FPR-8-826
	cmpl	$16, 8(%ecx)
	je	narrowing-FPR-8-1627
	cmpl	$32, 8(%ecx)
	je	narrowing-FPR-8-3228
	cmpl	$64, 8(%ecx)
	je	narrowing-FPR-8-6429
	jmp	_error
width-FPR-16B:
	cmpl	$8, 8(%ecx)
	je	narrowing-FPR-16-82A
	cmpl	$16, 8(%ecx)
	je	narrowing-FPR-16-162B
	cmpl	$32, 8(%ecx)
	je	narrowing-FPR-16-322C
	cmpl	$64, 8(%ecx)
	je	narrowing-FPR-16-642D
	jmp	_error
width-FPR-32C:
	cmpl	$8, 8(%ecx)
	je	narrowing-FPR-32-82E
	cmpl	$16, 8(%ecx)
	je	narrowing-FPR-32-162F
	cmpl	$32, 8(%ecx)
	je	narrowing-FPR-32-3230
	cmpl	$64, 8(%ecx)
	je	narrowing-FPR-32-6431
	jmp	_error
width-FPR-64D:
	cmpl	$8, 8(%ecx)
	je	narrowing-FPR-64-832
	cmpl	$16, 8(%ecx)
	je	narrowing-FPR-64-1633
	cmpl	$32, 8(%ecx)
	je	narrowing-FPR-64-3234
	cmpl	$64, 8(%ecx)
	je	narrowing-FPR-64-6435
	jmp	_error
width-STK-8E:
	cmpl	$8, 8(%ecx)
	je	narrowing-STK-8-836
	cmpl	$16, 8(%ecx)
	je	narrowing-STK-8-1637
	cmpl	$32, 8(%ecx)
	je	narrowing-STK-8-3238
	cmpl	$64, 8(%ecx)
	je	narrowing-STK-8-6439
	jmp	_error
width-STK-16F:
	cmpl	$8, 8(%ecx)
	je	narrowing-STK-16-83A
	cmpl	$16, 8(%ecx)
	je	narrowing-STK-16-163B
	cmpl	$32, 8(%ecx)
	je	narrowing-STK-16-323C
	cmpl	$64, 8(%ecx)
	je	narrowing-STK-16-643D
	jmp	_error
width-STK-3210:
	cmpl	$8, 8(%ecx)
	je	narrowing-STK-32-83E
	cmpl	$16, 8(%ecx)
	je	narrowing-STK-32-163F
	cmpl	$32, 8(%ecx)
	je	narrowing-STK-32-3240
	cmpl	$64, 8(%ecx)
	je	narrowing-STK-32-6441
	jmp	_error
width-STK-6411:
	cmpl	$8, 8(%ecx)
	je	narrowing-STK-64-842
	cmpl	$16, 8(%ecx)
	je	narrowing-STK-64-1643
	cmpl	$32, 8(%ecx)
	je	narrowing-STK-64-3244
	cmpl	$64, 8(%ecx)
	je	narrowing-STK-64-6445
	jmp	_error
width-FSTK-812:
	cmpl	$8, 8(%ecx)
	je	narrowing-FSTK-8-846
	cmpl	$16, 8(%ecx)
	je	narrowing-FSTK-8-1647
	cmpl	$32, 8(%ecx)
	je	narrowing-FSTK-8-3248
	cmpl	$64, 8(%ecx)
	je	narrowing-FSTK-8-6449
	jmp	_error
width-FSTK-1613:
	cmpl	$8, 8(%ecx)
	je	narrowing-FSTK-16-84A
	cmpl	$16, 8(%ecx)
	je	narrowing-FSTK-16-164B
	cmpl	$32, 8(%ecx)
	je	narrowing-FSTK-16-324C
	cmpl	$64, 8(%ecx)
	je	narrowing-FSTK-16-644D
	jmp	_error
width-FSTK-3214:
	cmpl	$8, 8(%ecx)
	je	narrowing-FSTK-32-84E
	cmpl	$16, 8(%ecx)
	je	narrowing-FSTK-32-164F
	cmpl	$32, 8(%ecx)
	je	narrowing-FSTK-32-3250
	cmpl	$64, 8(%ecx)
	je	narrowing-FSTK-32-6451
	jmp	_error
width-FSTK-6415:
	cmpl	$8, 8(%ecx)
	je	narrowing-FSTK-64-852
	cmpl	$16, 8(%ecx)
	je	narrowing-FSTK-64-1653
	cmpl	$32, 8(%ecx)
	je	narrowing-FSTK-64-3254
	cmpl	$64, 8(%ecx)
	je	narrowing-FSTK-64-6455
	jmp	_error
narrowing-GPR-8-816:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-8-8-stk56
	jmp	_error
narrowing-GPR-8-1617:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-8-16-stk57
	jmp	_error
narrowing-GPR-8-3218:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-8-32-stk58
	jmp	_error
narrowing-GPR-8-6419:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-8-64-stk59
	jmp	_error
narrowing-GPR-16-81A:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-16-8-stk5A
	jmp	_error
narrowing-GPR-16-161B:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-16-16-stk5B
	jmp	_error
narrowing-GPR-16-321C:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-16-32-stk5C
	jmp	_error
narrowing-GPR-16-641D:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-16-64-stk5D
	jmp	_error
narrowing-GPR-32-81E:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-32-8-stk5E
	jmp	_error
narrowing-GPR-32-161F:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-32-16-stk5F
	jmp	_error
narrowing-GPR-32-3220:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-32-32-stk60
	jmp	_error
narrowing-GPR-32-6421:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-32-64-stk61
	jmp	_error
narrowing-GPR-64-822:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-64-8-stk62
	jmp	_error
narrowing-GPR-64-1623:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-64-16-stk63
	jmp	_error
narrowing-GPR-64-3224:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-64-32-stk64
	jmp	_error
narrowing-GPR-64-6425:
	cmpl	$0, 12(%ecx)
	je	loc-GPR-64-64-stk65
	jmp	_error
narrowing-FPR-8-826:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-8-8-stk66
	jmp	_error
narrowing-FPR-8-1627:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-8-16-stk67
	jmp	_error
narrowing-FPR-8-3228:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-8-32-stk68
	jmp	_error
narrowing-FPR-8-6429:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-8-64-stk69
	jmp	_error
narrowing-FPR-16-82A:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-16-8-stk6A
	jmp	_error
narrowing-FPR-16-162B:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-16-16-stk6B
	jmp	_error
narrowing-FPR-16-322C:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-16-32-stk6C
	jmp	_error
narrowing-FPR-16-642D:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-16-64-stk6D
	jmp	_error
narrowing-FPR-32-82E:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-32-8-stk6E
	jmp	_error
narrowing-FPR-32-162F:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-32-16-stk6F
	jmp	_error
narrowing-FPR-32-3230:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-32-32-stk70
	jmp	_error
narrowing-FPR-32-6431:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-32-64-stk71
	jmp	_error
narrowing-FPR-64-832:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-64-8-stk72
	jmp	_error
narrowing-FPR-64-1633:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-64-16-stk73
	jmp	_error
narrowing-FPR-64-3234:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-64-32-stk74
	jmp	_error
narrowing-FPR-64-6435:
	cmpl	$0, 12(%ecx)
	je	loc-FPR-64-64-stk75
	jmp	_error
narrowing-STK-8-836:
	cmpl	$0, 12(%ecx)
	je	loc-STK-8-8-stk76
	jmp	_error
narrowing-STK-8-1637:
	cmpl	$0, 12(%ecx)
	je	loc-STK-8-16-stk77
	jmp	_error
narrowing-STK-8-3238:
	cmpl	$0, 12(%ecx)
	je	loc-STK-8-32-stk78
	jmp	_error
narrowing-STK-8-6439:
	cmpl	$0, 12(%ecx)
	je	loc-STK-8-64-stk79
	jmp	_error
narrowing-STK-16-83A:
	cmpl	$0, 12(%ecx)
	je	loc-STK-16-8-stk7A
	jmp	_error
narrowing-STK-16-163B:
	cmpl	$0, 12(%ecx)
	je	loc-STK-16-16-stk7B
	jmp	_error
narrowing-STK-16-323C:
	cmpl	$0, 12(%ecx)
	je	loc-STK-16-32-stk7C
	jmp	_error
narrowing-STK-16-643D:
	cmpl	$0, 12(%ecx)
	je	loc-STK-16-64-stk7D
	jmp	_error
narrowing-STK-32-83E:
	cmpl	$0, 12(%ecx)
	je	loc-STK-32-8-stk7E
	jmp	_error
narrowing-STK-32-163F:
	cmpl	$0, 12(%ecx)
	je	loc-STK-32-16-stk7F
	jmp	_error
narrowing-STK-32-3240:
	cmpl	$0, 12(%ecx)
	je	loc-STK-32-32-stk80
	jmp	_error
narrowing-STK-32-6441:
	cmpl	$0, 12(%ecx)
	je	loc-STK-32-64-stk81
	jmp	_error
narrowing-STK-64-842:
	cmpl	$0, 12(%ecx)
	je	loc-STK-64-8-stk82
	jmp	_error
narrowing-STK-64-1643:
	cmpl	$0, 12(%ecx)
	je	loc-STK-64-16-stk83
	jmp	_error
narrowing-STK-64-3244:
	cmpl	$0, 12(%ecx)
	je	loc-STK-64-32-stk84
	jmp	_error
narrowing-STK-64-6445:
	cmpl	$0, 12(%ecx)
	je	loc-STK-64-64-stk85
	jmp	_error
narrowing-FSTK-8-846:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-8-8-stk86
	jmp	_error
narrowing-FSTK-8-1647:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-8-16-stk87
	jmp	_error
narrowing-FSTK-8-3248:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-8-32-stk88
	jmp	_error
narrowing-FSTK-8-6449:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-8-64-stk89
	jmp	_error
narrowing-FSTK-16-84A:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-16-8-stk8A
	jmp	_error
narrowing-FSTK-16-164B:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-16-16-stk8B
	jmp	_error
narrowing-FSTK-16-324C:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-16-32-stk8C
	jmp	_error
narrowing-FSTK-16-644D:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-16-64-stk8D
	jmp	_error
narrowing-FSTK-32-84E:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-32-8-stk8E
	jmp	_error
narrowing-FSTK-32-164F:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-32-16-stk8F
	jmp	_error
narrowing-FSTK-32-3250:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-32-32-stk90
	jmp	_error
narrowing-FSTK-32-6451:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-32-64-stk91
	jmp	_error
narrowing-FSTK-64-852:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-64-8-stk92
	jmp	_error
narrowing-FSTK-64-1653:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-64-16-stk93
	jmp	_error
narrowing-FSTK-64-3254:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-64-32-stk94
	jmp	_error
narrowing-FSTK-64-6455:
	cmpl	$0, 12(%ecx)
	je	loc-FSTK-64-64-stk95
	jmp	_error
loc-GPR-8-8-stk56:
	jmp	interp97
	jmp	_error
loc-GPR-8-16-stk57:
	jmp	interp97
	jmp	_error
loc-GPR-8-32-stk58:
	jmp	interp97
	jmp	_error
loc-GPR-8-64-stk59:
	jmp	interp97
	jmp	_error
loc-GPR-16-8-stk5A:
	jmp	interp97
	jmp	_error
loc-GPR-16-16-stk5B:
	jmp	interp97
	jmp	_error
loc-GPR-16-32-stk5C:
	jmp	interp97
	jmp	_error
loc-GPR-16-64-stk5D:
	jmp	interp97
	jmp	_error
loc-GPR-32-8-stk5E:
	jmp	interp97
	jmp	_error
loc-GPR-32-16-stk5F:
	jmp	interp97
	jmp	_error
loc-GPR-32-32-stk60:
	jmp	interp97
	jmp	_error
loc-GPR-32-64-stk61:
	jmp	interp97
	jmp	_error
loc-GPR-64-8-stk62:
	jmp	interp97
	jmp	_error
loc-GPR-64-16-stk63:
	jmp	interp97
	jmp	_error
loc-GPR-64-32-stk64:
	jmp	interp97
	jmp	_error
loc-GPR-64-64-stk65:
	jmp	interp97
	jmp	_error
loc-FPR-8-8-stk66:
	jmp	interp97
	jmp	_error
loc-FPR-8-16-stk67:
	jmp	interp97
	jmp	_error
loc-FPR-8-32-stk68:
	jmp	interp97
	jmp	_error
loc-FPR-8-64-stk69:
	jmp	interp97
	jmp	_error
loc-FPR-16-8-stk6A:
	jmp	interp97
	jmp	_error
loc-FPR-16-16-stk6B:
	jmp	interp97
	jmp	_error
loc-FPR-16-32-stk6C:
	jmp	interp97
	jmp	_error
loc-FPR-16-64-stk6D:
	jmp	interp97
	jmp	_error
loc-FPR-32-8-stk6E:
	jmp	interp97
	jmp	_error
loc-FPR-32-16-stk6F:
	jmp	interp97
	jmp	_error
loc-FPR-32-32-stk70:
	jmp	interp97
	jmp	_error
loc-FPR-32-64-stk71:
	jmp	interp97
	jmp	_error
loc-FPR-64-8-stk72:
	jmp	interp97
	jmp	_error
loc-FPR-64-16-stk73:
	jmp	interp97
	jmp	_error
loc-FPR-64-32-stk74:
	jmp	interp97
	jmp	_error
loc-FPR-64-64-stk75:
	jmp	interp97
	jmp	_error
loc-STK-8-8-stk76:
	movzbl	20(%ecx), %eax
	movl	12(%ecx), %edx
	movb	%eax, (%esp,%edx,1)
	jmp	interp97
	jmp	_error
loc-STK-8-16-stk77:
	movzbl	20(%ecx), %eax
	movl	12(%ecx), %ebx
	movb	%eax, (%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-STK-8-32-stk78:
	movzbl	20(%ecx), %eax
	movl	12(%ecx), %esi
	movb	%eax, (%esp,%esi,1)
	jmp	interp97
	jmp	_error
loc-STK-8-64-stk79:
	movzbl	20(%ecx), %eax
	movl	12(%ecx), %edi
	movb	%eax, (%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-STK-16-8-stk7A:
	movzwl	20(%ecx), %edx
	movl	12(%ecx), %ebx
	movw	%edx, (%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-STK-16-16-stk7B:
	movzwl	20(%ecx), %esi
	movl	12(%ecx), %edi
	movw	%esi, (%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-STK-16-32-stk7C:
	movzwl	20(%ecx), %edx
	movl	12(%ecx), %ebx
	movw	%edx, (%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-STK-16-64-stk7D:
	movzwl	20(%ecx), %esi
	movl	12(%ecx), %edi
	movw	%esi, (%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-STK-32-8-stk7E:
	movl	20(%ecx), %edx
	movl	12(%ecx), %ebx
	movl	%edx, (%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-STK-32-16-stk7F:
	movl	20(%ecx), %esi
	movl	12(%ecx), %edi
	movl	%esi, (%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-STK-32-32-stk80:
	movl	20(%ecx), %edx
	movl	12(%ecx), %ebx
	movl	%edx, (%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-STK-32-64-stk81:
	movl	20(%ecx), %esi
	movl	12(%ecx), %edi
	movl	%esi, (%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-STK-64-8-stk82:
	jmp	interp97
	jmp	_error
loc-STK-64-16-stk83:
	jmp	interp97
	jmp	_error
loc-STK-64-32-stk84:
	jmp	interp97
	jmp	_error
loc-STK-64-64-stk85:
	jmp	interp97
	jmp	_error
loc-FSTK-8-8-stk86:
	jmp	interp97
	jmp	_error
loc-FSTK-8-16-stk87:
	jmp	interp97
	jmp	_error
loc-FSTK-8-32-stk88:
	jmp	interp97
	jmp	_error
loc-FSTK-8-64-stk89:
	jmp	interp97
	jmp	_error
loc-FSTK-16-8-stk8A:
	jmp	interp97
	jmp	_error
loc-FSTK-16-16-stk8B:
	jmp	interp97
	jmp	_error
loc-FSTK-16-32-stk8C:
	jmp	interp97
	jmp	_error
loc-FSTK-16-64-stk8D:
	jmp	interp97
	jmp	_error
loc-FSTK-32-8-stk8E:
	movl	12(%ecx), %edx
	flds	20(%ecx)
	fstps	(%esp,%edx,1)
	jmp	interp97
	jmp	_error
loc-FSTK-32-16-stk8F:
	movl	12(%ecx), %ebx
	flds	20(%ecx)
	fstps	(%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-FSTK-32-32-stk90:
	movl	12(%ecx), %esi
	flds	20(%ecx)
	fstps	(%esp,%esi,1)
	jmp	interp97
	jmp	_error
loc-FSTK-32-64-stk91:
	movl	12(%ecx), %edi
	flds	20(%ecx)
	fstps	(%esp,%edi,1)
	jmp	interp97
	jmp	_error
loc-FSTK-64-8-stk92:
	movl	12(%ecx), %edx
	fldl	20(%ecx)
	fstpl	(%esp,%edx,1)
	jmp	interp97
	jmp	_error
loc-FSTK-64-16-stk93:
	movl	12(%ecx), %ebx
	fldl	20(%ecx)
	fstpl	(%esp,%ebx,1)
	jmp	interp97
	jmp	_error
loc-FSTK-64-32-stk94:
	movl	12(%ecx), %esi
	fldl	20(%ecx)
	fstpl	(%esp,%esi,1)
	jmp	interp97
	jmp	_error
loc-FSTK-64-64-stk95:
	movl	12(%ecx), %edi
	fldl	20(%ecx)
	fstpl	(%esp,%edi,1)
	jmp	interp97
	jmp	_error
gotoC98:
	/* Liveout:  GP={%eax}  */
	call	*8(%ebp)
	leave
	/* live= GP={%edi %esi %ebx} spilled=  */
	ret
	.globl	_VarargInterp
